# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build the Android app (and optionally deploy)"
  lane :deploy do
    # Build the APK (or AAB). Adjust the task if needed.
    gradle(task: "assembleRelease")
    
    # For a proof-of-concept, we can skip actual deployment.
    # To actually deploy later, uncomment and configure the supply action:
    #
    # supply(
    #   apk: "app/build/outputs/apk/release/app-release.apk",
    #   track: "beta",
    #   json_key: ENV["GOOGLE_PLAY_JSON_KEY"]
    # )
    
    UI.message "Build successful. (Deployment step skipped for POC)"
  end
end

end
